### ISSUE TITLE
R register emulation

### ISSUE THREAD

**Issue by EtchedPixels** [TimothyPMann/xtrs#6]
Because R is incremented using the bottom end of the 16bit PC incrementer logic only the low 7bits roll over. While it should really use M1 cycle counts to get the right R value (and fix copy protections) it's also the case some crazy apps merely hide a bit in the top value of R which is user settable.

**Comment by TimothyPMann** [comment]
Huh, I remember hearing about this before and I thought I had improved it or merged a patch, but I see I still have the cheesy implementation of LD A, R where all 8 bits are random.

I don't think I'm up for implementing and debugging M1 cycle count, but at least I can change the high order bit to be storage instead of random.

**Comment by TimothyPMann** [comment]
I've pushed a change that fixes the high-order bit but leaves the 7 low-order bits as random.
